### ISSUE TITLE
Is this just a graphical template?

### ISSUE THREAD

**Issue by kemperflow** [Alvish0407/spotify-redesign#5]
Based on the description from Flutterflow saying that all the code was available on GitHub, is there actual underpinning code to handle the auth/sign-in and music play, etc or is this just a set of graphics and animations?

**Comment by Alvish0407** [comment]
> Based on the description from Flutterflow saying that all the code was available on GitHub, is there actual underpinning code to handle the auth/sign-in and music play, etc or is this just a set of graphics and animations?

This is just a graphical template. No auth or API integrated.
